/**
 * Top 200 most prescribed generic drug names in the US.
 * Source: Based on CMS/IQVIA data on prescription volume.
 * These cover ~90%+ of real-world prescriptions.
 *
 * Names are lowercase for case-insensitive matching against RxNorm.
 */
export const TOP_200_DRUGS: readonly string[] = [
  // Cardiovascular / antihypertensive
  "lisinopril",
  "amlodipine",
  "metoprolol",
  "losartan",
  "hydrochlorothiazide",
  "atorvastatin",
  "simvastatin",
  "rosuvastatin",
  "carvedilol",
  "furosemide",
  "spironolactone",
  "ramipril",
  "enalapril",
  "valsartan",
  "diltiazem",
  "verapamil",
  "nifedipine",
  "bisoprolol",
  "nebivolol",
  "olmesartan",
  "irbesartan",
  "candesartan",
  "hydralazine",
  "clonidine",
  "prazosin",
  "isosorbide mononitrate",
  "digoxin",
  "warfarin",
  "clopidogrel",
  "apixaban",
  "rivaroxaban",
  "aspirin",
  "pravastatin",
  "lovastatin",
  "fenofibrate",
  "gemfibrozil",
  "ezetimibe",
  "nitroglycerin",
  "amiodarone",
  "dronedarone",

  // Diabetes / metabolic
  "metformin",
  "glipizide",
  "glyburide",
  "glimepiride",
  "sitagliptin",
  "linagliptin",
  "saxagliptin",
  "empagliflozin",
  "dapagliflozin",
  "canagliflozin",
  "pioglitazone",
  "insulin glargine",
  "insulin aspart",
  "insulin lispro",
  "insulin regular",
  "insulin detemir",
  "liraglutide",
  "semaglutide",
  "dulaglutide",
  "exenatide",

  // Respiratory
  "albuterol",
  "montelukast",
  "fluticasone",
  "budesonide",
  "tiotropium",
  "salmeterol",
  "formoterol",
  "ipratropium",
  "beclomethasone",
  "mometasone",
  "cetirizine",
  "loratadine",
  "fexofenadine",
  "levocetirizine",
  "desloratadine",
  "pseudoephedrine",
  "guaifenesin",
  "dextromethorphan",
  "benzonatate",
  "roflumilast",

  // GI / acid
  "omeprazole",
  "pantoprazole",
  "esomeprazole",
  "lansoprazole",
  "rabeprazole",
  "famotidine",
  "ranitidine",
  "ondansetron",
  "promethazine",
  "metoclopramide",
  "dicyclomine",
  "hyoscyamine",
  "loperamide",
  "bismuth subsalicylate",
  "polyethylene glycol",
  "lactulose",
  "docusate",
  "senna",
  "mesalamine",
  "sulfasalazine",

  // CNS / psychiatric
  "sertraline",
  "escitalopram",
  "fluoxetine",
  "paroxetine",
  "citalopram",
  "fluvoxamine",
  "duloxetine",
  "venlafaxine",
  "desvenlafaxine",
  "bupropion",
  "trazodone",
  "mirtazapine",
  "amitriptyline",
  "nortriptyline",
  "imipramine",
  "doxepin",
  "clomipramine",
  "alprazolam",
  "clonazepam",
  "diazepam",
  "lorazepam",
  "temazepam",
  "zolpidem",
  "eszopiclone",
  "hydroxyzine",
  "buspirone",
  "aripiprazole",
  "quetiapine",
  "olanzapine",
  "risperidone",
  "ziprasidone",
  "haloperidol",
  "lithium",
  "valproic acid",
  "lamotrigine",
  "carbamazepine",
  "oxcarbazepine",
  "topiramate",
  "levetiracetam",
  "phenytoin",

  // Pain / anti-inflammatory / musculoskeletal
  "acetaminophen",
  "ibuprofen",
  "naproxen",
  "meloxicam",
  "celecoxib",
  "diclofenac",
  "ketorolac",
  "indomethacin",
  "tramadol",
  "oxycodone",
  "hydrocodone",
  "codeine",
  "morphine",
  "fentanyl",
  "buprenorphine",
  "naloxone",
  "naltrexone",
  "cyclobenzaprine",
  "methocarbamol",
  "tizanidine",
  "baclofen",
  "gabapentin",
  "pregabalin",
  "duloxetine",
  "capsaicin",
  "lidocaine",

  // Antibiotics / anti-infectives
  "amoxicillin",
  "amoxicillin-clavulanate",
  "azithromycin",
  "doxycycline",
  "ciprofloxacin",
  "levofloxacin",
  "metronidazole",
  "clindamycin",
  "trimethoprim-sulfamethoxazole",
  "nitrofurantoin",
  "cephalexin",
  "cefdinir",
  "cefuroxime",
  "penicillin v",
  "dicloxacillin",
  "vancomycin",
  "fluconazole",
  "itraconazole",
  "terbinafine",
  "acyclovir",
  "valacyclovir",
  "oseltamivir",
  "doxycycline hyclate",
  "minocycline",
  "clarithromycin",

  // Hormones / thyroid / reproductive
  "levothyroxine",
  "liothyronine",
  "prednisone",
  "prednisolone",
  "methylprednisolone",
  "dexamethasone",
  "hydrocortisone",
  "estradiol",
  "progesterone",
  "norethindrone",
  "medroxyprogesterone",
  "testosterone",
  "finasteride",
  "tamsulosin",
  "dutasteride",
  "sildenafil",
  "tadalafil",
  "vardenafil",
  "alendronate",
  "risedronate",

  // Urinary / renal
  "oxybutynin",
  "tolterodine",
  "solifenacin",
  "mirabegron",
  "desmopressin",
  "phenazopyridine",
  "trimethoprim",

  // Neurological / other
  "donepezil",
  "memantine",
  "rivastigmine",
  "galantamine",
  "sumatriptan",
  "rizatriptan",
  "topiramate",
  "propranolol",
  "methylphenidate",
  "amphetamine salts",
  "atomoxetine",
  "lisdexamfetamine",
  "modafinil",
  "armodafinil",
  "zonisamide",
  "lacosamide",
  "brivaracetam",
] as const;
